# Generated by Django 5.2.5 on 2025-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('idNumber', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('venueType', models.CharField(choices=[('', 'Select type'), ('office', 'Office'), ('meeting_room', 'Meeting Room'), ('conference_hall', 'Conference Hall'), ('event_space', 'Event Space'), ('other', 'Other')], default='', max_length=255)),
                ('size', models.CharField(blank=True, default='0', max_length=10, verbose_name='Size m²')),
                ('capacity', models.CharField(blank=True, default='0', max_length=10, verbose_name='Capacity')),
            ],
        ),
    ]
