# Generated by Django 5.2.5 on 2025-08-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
